# packages in environment at /home/leelasd/miniconda3/envs/denovo:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3  
certifi                   2019.11.28               py37_0  
cffi                      1.13.2           py37h2e261b9_0  
cudatoolkit               10.1.243             h6bb024c_0  
decorator                 4.4.1                      py_0    conda-forge
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
glib                      2.63.1               h5a9c865_0  
icu                       58.2                 h9c2bf20_1  
intel-openmp              2019.4                      243  
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.2                   py37_0    conda-forge
joblib                    0.14.1                     py_0    anaconda
jpeg                      9b                   h024ee3a_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.17.4           py37hc1035e2_0  
numpy-base                1.17.4           py37hde5b4d6_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1d               h7b6447c_3  
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
parso                     0.5.2                      py_0    conda-forge
pcre                      8.43                 he6710b0_0  
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    7.0.0            py37hb39fc2d_0  
pip                       19.3.1                   py37_0  
pixman                    0.38.0               h7b6447c_0  
prompt_toolkit            3.0.2                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-boost                  1.67.0           py37h04863e7_4  
pycparser                 2.19                     py37_0  
pygments                  2.5.2                      py_0    conda-forge
python                    3.7.6                h0371630_1  
python-dateutil           2.8.1                      py_0    conda-forge
pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2019.3                     py_0    conda-forge
rdkit                     2019.09.2.0      py37hc20afe1_1    rdkit
readline                  7.0                  h7b6447c_5  
scikit-learn              0.22             py37hd81dba3_0    anaconda
scipy                     1.3.2            py37h7c811a0_0    anaconda
setuptools                44.0.0                   py37_0  
six                       1.13.0                   py37_0  
sqlite                    3.30.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torchvision               0.4.2                py37_cu101    pytorch
tqdm                      4.41.1                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
